#!/usr/bin/perl -w
use File::Find;
my $newVersion=24000;
my $newVersionName=2.4;
my $reg = ".*.java";
my @curDir = @ARGV;
my @dirs;
find(\&PrintName,@curDir);
sub PrintName{
	my $path;
	if(/$reg/){
		$path = $File::Find::name;
		#$path = $_;
		#$path =~ m/pra.*/g;
		#print $path."\n";
		push @dirs,$path;
	}
}

$^I = ".bak";
@ARGV = @dirs;
#print join "\n",@ARGV;
while (<>) {
	#if(/^#!/){
	#	$_.= "#Copyright (C) 2013 by CF\n";
	#}
    #s/android:versionCode=\".*\"/android:versionCode=\"$newVersion\"/;
    #s/android:versionName=\".*\"/android:versionName=\"$newVersionName\"/; 
    #s/android:name=\"QQGameHallAuthorVer\" android:value=\".*\"/android:name=\"QQGameHallAuthorVer\" android:value=\"$newVersion\"/; 
	if(/VMRuntime/){
		$_= "\/\/ $_";
	}
	print;
}
