#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
#use strict;
#use warnings;
use Data::Dumper;

my @fileA = qw(小明 小王 小李 小东 小蔡 小杨 小红);
my @fileB = qw(小明 小王 小红);
my @fileC = qw(小红 小黄 小杨);
my @fileD = qw(小红 小蔡 小牛);
my %hashb;
my %hashc;
my %hashd;

foreach my $item (@fileB){
    $hashb{$item} = 1;
}
foreach my $item (@fileC){
    $hashc{$item} = 1;
}
foreach my $item (@fileD){
    $hashd{$item} = 1;
}

print "file A:  file B:  file C:  file D:\n";
foreach my $item (@fileA){
    if($hashb{$item}){
        print "$item   Y";
    }
    else
    {
        print "$item  N";
    }

    if($hashc{$item}){
        print "   Y";
    }
    else
    {
        print "   N";
    }

    if($hashd{$item}){
        print "   Y\n";
    }
    else
    {
        print "   N\n";
    }

}
#print Dumper(\%hash);
#print map {"    $_\n"}, grep { -s<1000 } @ARGV;

__DATA__
ABC = A1_B1;
ABD = C1_D1;
A1 = D0_A0;
B1 = A1_ABD;
C1 = C0;
D1 = B0_C1;
