#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
#use strict;
#use warnings;
use Data::Dumper;

open IN,"1";
open OUT,">","result.txt";
my %hash = ();
my $line = 0;
while(<IN>){
    chomp;
    my @tmp = sort {$a <=> $b} split;
    $hash{$tmp[0]}{$tmp[1]}{$tmp[2]}++;
    $line++;
    last if $line > 10000000;
}
print "sortDone\n";
while(my ($cc)=each %hash){
    print OUT $cc,"\n";
}
#print map {"    $_\n"}, grep { -s<1000 } @ARGV;

__DATA__
ABC = A1_B1;
ABD = C1_D1;
A1 = D0_A0;
B1 = A1_ABD;
C1 = C0;
D1 = B0_C1;
