#!/usr/bin/perl -w
##Copyright (C) 2013 by CF   
use strict;
use warnings;
use Data::Dumper;

my $textA = <<EOF;
1825_8911
69_4495
60213_64364
301_3270
EOF


my @linesA = split /\n/,$textA;

my %A = map { chomp; $_ ,1 } @linesA;
#print Dumper(\%A);
while (<DATA>) {
    chomp;
    my ($key) = /^\S+?_(.*)$/;
    if (exists $A{$key}){
        print $_.<DATA>;
    }else{ <DATA>; }
}
#ok one
#while (<DATA>) {
#    chomp;
#    foreach my $li(keys %A){
#        if($_ =~ /$li/){
#            print "$_\n";
#        }
#    }
#}
__DATA__
>dsgfdsg_60213_64364
1111111234354546
>dgfdg_301_3270
dgdfgdfbhgnbtg
>bbbb_69_4495
cccccbbgnghn
>aaaaa_1825_8911
dfggggggggggg23dfsgdsd
