#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
use strict;
use warnings;
use Data::Dumper;

while(<DATA>){
    chomp;
    my($sName,$sK1,$sK2,@aData) = split;
    my %hKey = ($sK1=>$sK1,'0'=>'0');
    foreach(@aData){
        s/(\S)/defined $hKey{$1}?$hKey{$1}:$sK2/ge;
    }
    $_ = join (" ",$sName,$sK1,$sK2,@aData);
    print "$_\n";
}
#print map {"    $_\n"}, grep { -s<1000 } @ARGV;

__DATA__
name1 A C AA SS AS SA 00
name2 A H WW WA AA AW 00
name3 A I AY YA YY AA 00
name4 C H CC CZ ZZ ZC 00
