#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
#use strict;
#use warnings;
use Data::Dumper;

my @files = qw /A B C D/;
my  $g;
print join "\t", @files, "\n";
my $all = shift @files;
for my $file(@files){
    open FH,$file or die $!;
    while(<FH>) {
        push @{$g->{$file}},$_;
    }
}
open FA,$all or die $!;
while(my $line = <FA> ) {
    chomp $line;
    print $line;
    my $letter;
    for my $file(@files) {
        for (@{ $g->{$file} }){
            $line eq $_ ? do { $letter = "y"; last } : do {$letter = "n"};
        }
        print "\t$letter";
    }
    print "\n";
}
print Dumper(\$g);
#print map {"    $_\n"}, grep { -s<1000 } @ARGV;

__DATA__
ABC = A1_B1;
ABD = C1_D1;
A1 = D0_A0;
B1 = A1_ABD;
C1 = C0;
D1 = B0_C1;
