#!/usr/bin/perl -w
##Copyright (C) 2013 by CF good...first mark the index ,second put the value 
use strict;
use warnings;
use Data::Dumper;

use List::Util qw(shuffle);

my @array = (1..100);
for (1 .. 100){
    print shuffle(@array)."\n";
}

