#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
#use strict;
#use warnings;
use Data::Dumper;

my $module = 11;
my @files = ();
my $lines;
for (0..$module-1){
    open $files[$_],">","map_$_.txt"
        or die "could not open map_$_.txt: $!";
}

while (<>){
    chomp;
    $lines++;
    print $lines."\n";
    my($f1,$f2,$f3) = sort {$a <=> $b} split ;
    print {$files[$lines % $module]} "$f1\t$f2\t$f3\n";
}
#print map {"    $_\n"}, grep { -s<1000 } @ARGV;

__DATA__
ABC = A1_B1;
ABD = C1_D1;
A1 = D0_A0;
B1 = A1_ABD;
C1 = C0;
D1 = B0_C1;
