#!/usr/bin/perl -w
#use utf8;
#binmode(STDIN,':encoding(utf8)');
#binmode(STDOUT,':encoding(utf8)');
#binmode(STDERR,':encoding(utf8)');
use Encode;
use strict;
#use LWP::Simple qw(get);
use LWP::Simple qw(get);
#my $config (XML::Simple->new()->XMLin('part1.xml'));
#print $config->{user};
#print Dumper (XML::Simple->new()->XMLin('part1.xml'));
my $url = shift || "http://gzbusnow.sinaapp.com/index.php?c=busrunningv2&a=query&keyword=B8";
my $content = get($url);
#print $content;
#print encode("utf-8",decode("utf-8",$content));
#if($content =~/<td>(.*)<\/td>\s*<td>(.*)<\/td>/) {
#while($content =~ m%<td>(.*)</td>%isg){
while($content =~ m%<td>([^`])<\/td>%isg){
	print $1;
	print "\n";
}
