#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
use strict;
use warnings;

open my $fh,'<','patterns.txt' or die "Could not open patterns.txt:$!";

my @array;
while(<$fh>){
    chomp;
    my $pattern = eval {qr/$_/} or do { warn "Invalid pattern:$@";next };
    push @array,$pattern;
}

#while(<>){
#    foreach my $pattern(@array){
#        print "Match of [$pattern] at line $. | $_" if /$pattern/;
#    }
#}

#be that simple:report one match
LINE:while(<>){
    foreach my $pattern (@array){
        if(/$pattern/){
            print "Match at line $. | $_" if /$pattern/;
            next LINE;
        }
    }
}


