#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
use strict;
use warnings;
use Data::Dumper;
use Cwd;
use File::Spec::Functions;

my $cwd = getcwd;
foreach my $file (glob (".* *")){
    print "   ",catfile( $cwd , $file ) , "\n";
}

#print Dumper(\%hash);


__DATA__
ABC = A1_B1;
ABD = C1_D1;
A1 = D0_A0;
B1 = A1_ABD;
C1 = C0;
D1 = B0_C1;
