#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
##put the filehandle to hash...
use strict;
use warnings;

opendir my $dh,"/tmp",or die "Could not open directory:$!";

foreach my $file(readdir($dh)){
    print "Skipper,I found $file\n";
}
