#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
# Storable::if you copy an array it's a shallow copy ,when it hava a reference,it will change by the shallow copy 
# Storable::dclone can help us have a deep copy.
use warnings;
use Data::Dumper;
use diagnostics;
use Storable;

my @provisions = qw( hat suncreen );
my @science_kit = qw( microscope radio );
push @provisions,\@science_kit;
my @packed = @{Storable::dclone \@provisions};

push @{$packed[2]}, 'blue_shirt';
print Data::Dumper->Dump(
    [\@provisions],
    [qw(*provisions)]
);
print Data::Dumper->Dump(
    [\@packed],
    [qw(*packed)]
);
__DATA__
name1 A C AA SS AS SA 00
name2 A H WW WA AA AW 00
name3 A I AY YA YY AA 00
name4 C H CC CZ ZZ ZC 00
