#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
#use strict;
#use warnings;
use Data::Dumper;

#my @files = glob "*.*";
#my $reg = <STDIN>;
#print "\$reg $reg\n";
#foreach (@files){
#    if(/out/){
#        print "$_\n";
#    } 
#}
#chdir;
while(1){
    print "Please enter a regular expression>";
    chomp(my $regex = <STDIN>);
    last unless( defined $regex && length $regex );
    print map {"   $_\n"} grep {eval{ /$regex/ }} glob(".* *" );
}
#print Dumper(\@files);
#@files = grep { -s<1000 } @files;
#print map {"    $_\n"}, @files;

__DATA__
name1 A C AA SS AS SA 00
name2 A H WW WA AA AW 00
name3 A I AY YA YY AA 00
name4 C H CC CZ ZZ ZC 00
