#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
##put the filehandle to hash...
use strict;
use warnings;

use IO::Null;
my $Debug = 1;
my $debug_fh = $Debug ? *STDOUT :IO::Null->new;
$debug_fh->print("Hey,the radio is not working!")
