#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
use strict;
use warnings;


#smart match 
#$string ~~ @patterns;

#solve match who
my %patterns = (
    Gilligan => qr/(?:Willie)?Gilligan/,
    'Mary Ann' => qr/Mary Ann/,
    Ginger => qr/Ginger/,
    Professor => qr/(?:The)?Professor/,
    Skipper =>qr/Skipper/,
    "A howell" =>qr/Mrs?. Howell/,
);

my $position = rightmost(
    'There is Mrs. Howell,Ginger, and Gilligan',
    #qr/Mary/,qr/Gin/,
    \%patterns
);

# my solve
#sub rightmost{
#    my($string,$patterns) = @_;
#
#    my $rightmost = -1;
#    foreach my $pattern (keys %$patterns){
#        $position = $string =~ m/$patterns->{$pattern}/ ? $-[0]:-1;
#        $rightmost = $position if $position > $rightmost;
#    }
#    return $rightmost;
#}
#
sub rightmost{
    my($string,$patterns) = @_;
    my($rightmost_position,$rightmost_key) = (-1,undef);
    while(my($key,$value) = each %$patterns){
        my $position = $string =~ m/$value/ ? $-[0]:-1;
        if($position > $rightmost_position){
            $rightmost_position = $position;
            $rightmost_key = $value;
        }
    }
    return $rightmost_key;
}

print "Rightmost match at position $position";


