#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
use strict;
use warnings;


#smart match 
#$string ~~ @patterns;

#solve match who
#my %patterns = (
#    Gilligan => qr/(?:Willie)?Gilligan/,
#    'Mary Ann' => qr/Mary Ann/,
#    Ginger => qr/Ginger/,
#    Professor => qr/(?:The)?Professor/,
#    Skipper =>qr/Skipper/,
#    "A howell" =>qr/Mrs?. Howell/,
#);
#
#my $name = 'Ginger';
#
#my ($match) = grep {$name =~ $patterns{$_}} keys %patterns;
#print "Match !$match\n" if $match;


