#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
# Storable::if you copy an array it's a shallow copy ,when it hava a reference,it will change by the shallow copy 
# Storable::dclone can help us have a deep copy.
use warnings;
use Data::Dumper;
use Storable;

my $data_file = "latest.data";
my %total_bytes ;
if(-e $data_file){
    my $data = Storable::retrieve($data_file);
    %total_bytes = %$data;
}
print Dumper(\%total_bytes);
my $all = "**All Machine **";
while(<>){
    next if /^#/;
    my($source,$destination,$bytes) = split;
    $total_bytes{$source}{$destination} += $bytes;
    $total_bytes{$source}{$all} += $bytes;
}
my @source = sort {$total_bytes{$b}{$all}<=>$total_bytes{$a}{$all}} keys %total_bytes;
for my $source (@source){
    print "$source: $total_bytes{$source}{$all} total  bytes sent\n";
    for my $destination (sort {$total_bytes{$source}{$b}<=>$total_bytes{$source}{$a}} keys %{ $total_bytes{$source} }){
            next if $destination eq $all;
        print "$source => $destination:","$total_bytes{$source}{$destination} bytes\n";
    }
    print "\n";
}
Storable::nstore \%total_bytes,"latest.data";
__DATA__
name1 A C AA SS AS SA 00
name2 A H WW WA AA AW 00
name3 A I AY YA YY AA 00
name4 C H CC CZ ZZ ZC 00
