#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
# 1 cmp sort hash 
use warnings;
use Data::Dumper;
use diagnostics;
my %total_bytes;
my $all = "**All Machine **";
while(<>){
    next if /^#/;
    my($source,$destination,$bytes) = split;
    $total_bytes{$source}{$destination} += $bytes;
    $total_bytes{$source}{$all} += $bytes;
}
my @source = sort {$total_bytes{$b}{$all}<=>$total_bytes{$a}{$all}} keys %total_bytes;
for my $source (@source){
    print "$source: $total_bytes{$source}{$all} total  bytes sent\n";
    for my $destination (sort {$total_bytes{$source}{$b}<=>$total_bytes{$source}{$a}} keys %{ $total_bytes{$source} }){
            next if $destination eq $all;
        print "$source => $destination:","$total_bytes{$source}{$destination} bytes\n";
    }
    print "\n";
}

#print Dumper(\%total_bytes);
__DATA__
name1 A C AA SS AS SA 00
name2 A H WW WA AA AW 00
name3 A I AY YA YY AA 00
name4 C H CC CZ ZZ ZC 00
