#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
@rocks = qw/ bedrock slate lava /;
print "The rocks before are:\n", @rocks ,"\n";
foreach $rock (@rocks){
	$rock = "\t$rock";
	$rock .="\n";
}
print "The rocks are:\n", @rocks;
