#!/usr/bin/perl -w
use strict;

use LWP::UserAgent;
use JSON;
use Data::Dumper;

my $browser = LWP::UserAgent -> new();
print "Please input the word\n";
chomp (my $input = <STDIN>);
my $response = $browser->post(
    'http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule&smartresult=ugc&sessionFrom=http://www.google.com.hk/url',
    [
        'type' => 'AUTO',
        'i' => "$input",
        'doctype' => 'json',
    ],
);
#my $result = $response->content;
#my $json = new JSON;
#my $obj = $json->decode($result);
#print Dumper $obj;
#my $trans = @{$obj->{"translateResult"}[0][0]->{"tgt"};
#print Dumper $trans;
if($response->is_success){
    my $result = $response->content;
    my $json = new JSON;
    my $obj = $json->decode($result);
    print Dumper $obj;
    my $trans = @{$obj->{'translateResult'}[0]}[0]->{"tgt"};
    $trans = "翻译结果:$trans" if $trans;
    my $string;
    eval{
        $string = join " ",@{$obj->{'smartResult'}->{"entries"}};
    };
    $trans = "$trans\n其它结果:$string" if $string;
    print $trans."\n" //"Not found\n";
}
