#!/usr/bin/perl -w
sub total{
	my $sum = 0;
	foreach (@_){
		$sum +=$_;
	}
	$sum;
}
my @fred =1..1000;
my $fred_total = total(@fred);
print "The total of \@fred is $fred_total.\n";
print "Enter some numbers on separate lines:";
my $user_total = total(<STDIN>);
print "The total of those number is $user_total.\n";
