#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
$names{"fred"}="flintstone";
$names{"barney"}="rubble";
$names{"wilma"}="flintstone";
print "Enter an name, then press Ctrl-D:\n";
chomp(my $name = <STDIN>);
print $names{$name};
