#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
##IO::Scalar
use strict;
use warnings;
use IO::Scalar;

my $string_log = "Gilligan 
good";
my $scalar_fh = IO::Scalar->new(\$string_log);
while(<$scalar_fh>){
    next unless /Gilligan/;
    print;
}

