#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! push @{$h->{$arr1[$_]}},$_    Greate,push an @array to $ or %hash  everyPerler knows that 
#use strict;
#use warnings;
use Data::Dumper;

my %gilligan_info = (
    name => 'Gilligan',
    hat  => 'White',
    shirt => 'Red' ,
    position => 'First Mate',
);

my %skipper_info = (
    name => 'Skipper',
    hat  => 'Black',
    shirt => 'Blue' ,
    position => 'Captain',
);
my @crew = (\%gilligan_info,\%skipper_info);
my $format = "%-15s %-7s %-7s %-15s\n";
printf $format,qw(name shirt hat position);
foreach my $crewmember (@crew){
    printf $format,@$crewmember{qw(name shirt hat position)};
}
#print map {"    $_\n"}, @files;

__DATA__
name1 A C AA SS AS SA 00
name2 A H WW WA AA AW 00
name3 A I AY YA YY AA 00
name4 C H CC CZ ZZ ZC 00
