#!/usr/bin/perl -w
##Copyright (C) 2013 by CF  !!!! 
use strict;
use warnings;
use Data::Dumper;
use File::Copy;

#my @datas;
#while(my $line =<>){
#    push @datas,$line;
#}
#for(my $i = 0;$i < @datas/2; $i ++ ){
#    print $datas[$i],"\n",$datas[$i+5],"\n";
#}
#

#
my $target_dir = "/tmp/tmp";
my @files_small_than_1000k = grep { -s $_< 1024*10 } glob("*");
copy $_ =>$target_dir for @files_small_than_1000k;
