#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
##Copyright (C) 2013 by CF
running_sum(5,6);
running_sum(1..3);
running_sum(4);

sub running_sum{
	state $sum=0;
	state @numbers;

	foreach my $number(@_){
		push @numbers,$number;
		$sum+=$number;
	}
	print "The sum of (@numbers) is $sum";
}
