#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
##Copyright (C) 2013 by CF
@rocks = qw( talc quartz jade obsidian );
print "How many rocks do you have?\n";
print "I hava @rocks rocks!\n";
print "I have ",scalar @rocks, " rocks!\n";
