#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
use strict;
use warnings;
use 5.010;

my $str= "The black cat climbed the green tree";

say substr $str,4,-11;
say substr $str,14,7,"jumped from";
say $str;
