#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
use strict;
use warnings;
use 5.010;

my @files = glob "pra*";
#my @sorted_files = sort @files;
#my @sorted_files = sort {length($a) <=> length($b)}@files;
my @sorted_files = sort {-s $a <=> -s $b} @files;

foreach my $file (@sorted_files){
	printf("%-15s %s\n",$file,-s $file);
}
