#!/usr/bin/perl -w
$pi = 3.141592654;
print "What is the radius?\n";
chomp($radius=<STDIN>);
$circ=2*$pi*$radius;
if($circ lt 0){
print "The circumference of a circle of radius $radius is 0.\n";
}else{
print "The circumference of a circle of radius $radius is $circ.\n";}
