#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
use strict;
use warnings;
use 5.010;

my $str= "The black cat jumped from the green tree";

say lc $str;
say uc $str;
say length $str;

say index $str,'cat';
say index $str,'dog';
say index $str,'The';
say index $str,'the';
