#!/usr/bin/perl -w
#my @numbers = qw(8 2 5 3 1 7);
#my @big_numbers = grep { $_ > 4} @numbers;
#print "@big_numbers\n";
use strict;
use warnings;

#my @names = qw(Foo Bar Baz);
#my $visitor = <STDIN>;
#chomp $visitor;
#if(grep {$visitor eq $_} @names){
#	print "Visitor $visitor is in the guest list\n";
#}else{
#	print "Visitor $visitor is NOT int the guest list\n";
#}
my $regex = shift;
print grep { $_ =~ /$regex/ } <>;
