#!/usr/bin/perl -w
##Copyright (C) 2013 by CF
use strict;
use warnings;
use 5.010;

#my $x= int 3.14;
#say $x;
my $z =int rand 200;
$z = $z + 1;
print $z;
while(<>){
	print $_."\n";
if($_ == $z){
	print "You are right\n";
}else{
	print "Try again\n";
}
}
