#!/usr/bin/perl -w
use strict;
use warnings;

my %WARNS;
local $SIG{__WARN__} = sub {
    my $message = shift;
#    return if $WARNS{$message}++;
    logger('warning',$message);
};

my $counter;
count();
print "$counter\n";
$counter = undef;
count();
sub count {
    $counter = $counter + 42;
}

sub logger {
    my ($level,$msg) = @_;
    if(open my $out,'>>','log.txt'){
        chomp $msg;
        print $out "$level - $msg\n";
    }

}
